/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SÄNTI MILOS (https://sketchfab.com/TEDIORE)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bmw-5-series-e34-12a7653285d54328bdaa6471f3fa3b02
Title: BMW 5 Series E34
*/

import React, { useRef, useState } from "react"
import { getFullPath } from "@/helpers/pathHelper"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import { easing } from "maath"
import * as THREE from "three"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshPhysicalMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    Badge: THREE.MeshPhysicalMaterial
    Light: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    Light2: THREE.MeshStandardMaterial
    bBMW_M3SportEvoE30_1990_CallipersCalliperA_Zone_Material1: THREE.MeshPhysicalMaterial
    material: THREE.MeshStandardMaterial
    Tire: THREE.MeshPhysicalMaterial
  }
}

// This Model doesnt merge the geometries and materials unlike like bmw-car.tsx

// @ts-expect-error temp ignore
export function BMWCar2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    getFullPath("/bmw_5_series_e34-v1.glb")
  ) as GLTFResult
  const carRef = useRef<THREE.Group>(null!)
  const frontRightWheelRef = useRef<THREE.Group>(null!)
  const frontLeftWheelRef = useRef<THREE.Group>(null!)

  const wheelRefs = {
    // Tire meshes: Object_46, Object_54, Object_62, Object_70
    frontRightTireRef: useRef<THREE.Mesh>(null!),
    backRightTireRef: useRef<THREE.Mesh>(null!),
    frontLeftTireRef: useRef<THREE.Mesh>(null!),
    backLeftTireRef: useRef<THREE.Mesh>(null!),

    // Wheel rim meshes: Object_42, Object_50, Object_58, Object_68
    frontRightRimRef: useRef<THREE.Mesh>(null!),
    backRightRimRef: useRef<THREE.Mesh>(null!),
    frontLeftRimRef: useRef<THREE.Mesh>(null!),
    backLeftRimRef: useRef<THREE.Mesh>(null!),
  }

  useFrame((_, delta) => {
    const rotationSpeed = 10 * delta

    wheelRefs.frontRightTireRef.current.rotation.x -= rotationSpeed
    wheelRefs.backRightTireRef.current.rotation.x -= rotationSpeed
    wheelRefs.frontRightRimRef.current.rotation.x -= rotationSpeed
    wheelRefs.backRightRimRef.current.rotation.x -= rotationSpeed

    wheelRefs.frontLeftTireRef.current.rotation.x += rotationSpeed
    wheelRefs.backLeftTireRef.current.rotation.x += rotationSpeed
    wheelRefs.frontLeftRimRef.current.rotation.x += rotationSpeed
    wheelRefs.backLeftRimRef.current.rotation.x += rotationSpeed
  })

  const [dummy] = useState(() => new THREE.Object3D())
  //   const { viewport } = useThree()

  //   useFrame((state, dt) => {
  //     const mouse = state.pointer
  //     const x = (mouse.x * viewport.width) / 12
  //     const y = (mouse.y * viewport.height) / 12
  //     dummy.lookAt(x, y, 1)
  //     dummy.lookAt(state.pointer.x / 2, 0, 1)
  //     easing.dampQ(carRef.current.quaternion, dummy.quaternion, 0.15, dt)
  //   })

  useFrame((state, dt) => {
    if (props.disableMouseTrackingAnimation) return

    const mouse = state.pointer
    const x = THREE.MathUtils.clamp(mouse.x, -1, 1)

    dummy.lookAt(x / 1.25, 0, 1)
    easing.dampQ(carRef.current.quaternion, dummy.quaternion, 0.15, dt)

    const steeringAmount = x * 0.7
    const steerSmoothing = 0.5

    if (frontRightWheelRef.current && frontLeftWheelRef.current) {
      easing.damp(
        frontRightWheelRef.current.rotation,
        "y",
        steeringAmount,
        steerSmoothing,
        dt
      )
      easing.damp(
        frontLeftWheelRef.current.rotation,
        "y",
        steeringAmount,
        steerSmoothing,
        dt
      )
    }
  })

  return (
    <group ref={carRef} position={[0, 0.2, 22]} {...props} dispose={null}>
      <mesh
        name="Object_4"
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="Object_6"
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        name="Object_8"
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        name="Object_10"
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        name="Object_12"
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Badge}
      />
      <mesh
        name="Object_14"
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        name="Object_16"
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        name="Object_18"
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        name="Object_20"
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.Light}
      />
      <mesh
        name="Object_22"
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        name="Object_24"
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        name="Object_26"
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        name="Object_28"
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        name="Object_30"
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        name="Object_32"
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.Light2}
      />
      <mesh
        name="Object_34"
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        name="Object_36"
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        name="Object_38"
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        name="Object_40"
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={
          materials.bBMW_M3SportEvoE30_1990_CallipersCalliperA_Zone_Material1
        }
        position={[0.822, 0.313, 1.42]}
      />
      {/* Front Right Wheel Rim (Object_42) */}
      <group ref={frontRightWheelRef} position={[0.822, 0.313, 1.42]}>
        {/* Rim */}
        <mesh
          name="Object_42"
          ref={wheelRefs.frontRightRimRef}
          castShadow
          receiveShadow
          geometry={nodes.Object_42.geometry}
          material={materials.material}
          position={[0, 0, 0]} // centered
        />
        {/* Badge */}
        <mesh
          name="Object_44"
          castShadow
          receiveShadow
          geometry={nodes.Object_44.geometry}
          material={materials.Badge}
          position={[0, 0, 0]}
        />
        {/* Tire */}
        <mesh
          name="Object_46"
          ref={wheelRefs.frontRightTireRef}
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials.Tire}
          position={[-0.06, 0, 0]}
        />
      </group>

      <mesh
        name="Object_48"
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={
          materials.bBMW_M3SportEvoE30_1990_CallipersCalliperA_Zone_Material1
        }
        position={[0.82, 0.313, -1.387]}
      />
      {/* Back Right Wheel Rim (Object_50) */}
      <mesh
        name="Object_50"
        ref={wheelRefs.backRightRimRef}
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials.material}
        position={[0.82, 0.313, -1.387]}
      />
      <mesh
        name="Object_52"
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials.Badge}
        position={[0.82, 0.313, -1.387]}
      />
      {/* Back Right Tire (Object_54) */}
      <mesh
        name="Object_54"
        ref={wheelRefs.backRightTireRef}
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials.Tire}
        position={[0.729, 0.313, -1.387]}
      />
      <mesh
        name="Object_56"
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={
          materials.bBMW_M3SportEvoE30_1990_CallipersCalliperA_Zone_Material1
        }
        position={[-0.822, 0.313, 1.42]}
      />
      {/* Front Left Wheel Rim (Object_58) */}
      <group ref={frontLeftWheelRef} position={[-0.822, 0.313, 1.42]}>
        {/* Rim */}
        <mesh
          name="Object_58"
          ref={wheelRefs.frontLeftRimRef}
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials.material}
          position={[0, 0, 0]}
        />
        {/* Badge */}
        <mesh
          name="Object_60"
          castShadow
          receiveShadow
          geometry={nodes.Object_60.geometry}
          material={materials.Badge}
          position={[0, 0, 0]}
        />
        {/* Tire */}
        <mesh
          name="Object_62"
          ref={wheelRefs.frontLeftTireRef}
          castShadow
          receiveShadow
          geometry={nodes.Object_62.geometry}
          material={materials.Tire}
          position={[0.06, 0, 0]} // inward offset (mirror of right)
        />
      </group>
      {/* Back Left Wheel Rim (Object_68) */}
      <mesh
        name="Object_68"
        ref={wheelRefs.backLeftRimRef}
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials.material}
        position={[-0.82, 0.313, -1.387]}
      />
      {/* Back Left Tire (Object_70) */}
      <mesh
        name="Object_70"
        ref={wheelRefs.backLeftTireRef}
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials.Tire}
        position={[-0.729, 0.313, -1.387]}
      />
    </group>
  )
}

useGLTF.preload(getFullPath("/bmw_5_series_e34-v1.glb"))
