/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SÄNTI MILOS (https://sketchfab.com/TEDIORE)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bmw-5-series-e34-12a7653285d54328bdaa6471f3fa3b02
Title: BMW 5 Series E34
*/

import React, { useRef } from "react"
import { getFullPath } from "@/helpers/pathHelper"
import { useGLTF } from "@react-three/drei"
import * as THREE from "three"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_12: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_32: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_46: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshPhysicalMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    Badge: THREE.MeshPhysicalMaterial
    Light: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    Light2: THREE.MeshStandardMaterial
    bBMW_M3SportEvoE30_1990_CallipersCalliperA_Zone_Material1: THREE.MeshPhysicalMaterial
    material: THREE.MeshStandardMaterial
    Tire: THREE.MeshPhysicalMaterial
  }
}

// @ts-expect-error temp ignore
export function BMWCar(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    getFullPath("/bmw_5_series_e34-v1-ktx.glb")
  ) as GLTFResult
  const tireRef = useRef<THREE.Mesh>(null)

  return (
    <group position={[0, 0.2, 0]} {...props} dispose={null}>
      <mesh
        name="Object_4"
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[0, 0.791, -0.125]}
        scale={2.359}
      />
      <mesh
        name="Object_6"
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.PaletteMaterial002}
        position={[0, 0.79, -0.108]}
        scale={2.28}
      />
      <mesh
        name="Object_8"
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.PaletteMaterial003}
        position={[0, 0.821, -0.124]}
        scale={2.366}
      />
      <mesh
        name="Object_12"
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Badge}
        position={[0, 0.6, -0.135]}
        scale={2.272}
      />
      <mesh
        name="Object_20"
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.Light}
        position={[0, 0.443, 1.494]}
        scale={0.861}
      />
      <mesh
        name="Object_22"
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.PaletteMaterial004}
        position={[0, 0.687, -0.117]}
        scale={2.238}
      />
      <mesh
        name="Object_32"
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.Light2}
        position={[0, 0.771, -2.347]}
        scale={0.809}
      />
      <mesh
        name="Object_40"
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={
          materials.bBMW_M3SportEvoE30_1990_CallipersCalliperA_Zone_Material1
        }
        position={[0, 0.283, -0.097]}
        scale={1.46}
      />
      <mesh
        name="Object_42"
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.material}
        position={[0, 0.313, 0.017]}
        scale={1.64}
      />
      <mesh
        ref={tireRef}
        name="Object_46"
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.Tire}
        position={[0, 0.313, 0.016]}
        scale={1.717}
      />
    </group>
  )
}

useGLTF.preload(getFullPath("/bmw_5_series_e34-v1-ktx.glb"))
