/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Luan (https://sketchfab.com/luanche)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamp-post-0d0f727a41194c6eb73c3ec9ac67ae98
Title: Lamp post
*/

import React from "react"
import { getFullPath } from "@/helpers/pathHelper"
import { useGLTF } from "@react-three/drei"
import * as THREE from "three"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    poste1_poste_0: THREE.Mesh
    poste1_luz_0: THREE.Mesh
  }
  materials: {
    poste: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
}

// @ts-expect-error temp ignore
export function LampPost(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    getFullPath("/lamp_post.glb")
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poste1_poste_0.geometry}
        material={materials.poste}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poste1_luz_0.geometry}
        material={materials.material}
        material-emissiveIntensity="2"
        // material-emissive="yellow"
      />
    </group>
  )
}

useGLTF.preload(getFullPath("/lamp_post.glb"))
