/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect, useRef } from "react"
import { getFullPath } from "@/helpers/pathHelper"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import { useControls } from "leva"
import * as THREE from "three"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Back_Wheel: THREE.Mesh
    Front_Wheel: THREE.Mesh
  }
  materials: {
    Base: THREE.MeshStandardMaterial
    Front_Wheel_Material: THREE.MeshStandardMaterial
    TeslaFrontLight: THREE.MeshStandardMaterial
    TeslaRearLight: THREE.MeshStandardMaterial
    ["Material.004"]: THREE.MeshStandardMaterial
    ["Material.001"]: THREE.MeshStandardMaterial
  }
}

// @ts-expect-error temp ignore
type GroupProps = JSX.IntrinsicElements["group"]

interface TeslaCyberTruckProps extends GroupProps {
  color?: string
  metalness?: number
  roughness?: number
}

export function TeslaCyberTruck({
  color: defaultColor = "#fff",
  metalness: defaultMetalness = 0.5,
  roughness: defaultRoughness = 0.5,
  ...props
}: TeslaCyberTruckProps) {
  const { nodes, materials } = useGLTF(
    getFullPath("/tesla_cybertruck-transformed.glb")
  ) as GLTFResult

  const frontWheelRef = useRef<THREE.Mesh>(null!)
  const backWheelRef = useRef<THREE.Mesh>(null!)

  const baseControls = useControls("Car Base Material", {
    color: { value: "#313131" },
    metalness: { value: 0.8, min: 0, max: 1 },
    roughness: { value: 0.5, min: 0, max: 1 },
  })

  const wheelControls = useControls("Car Wheels", {
    color: { value: "#1a1a1a" },
    metalness: { value: 0.5, min: 0, max: 1 },
    roughness: { value: 0.5, min: 0, max: 1 },
  })

  const frontLightControls = useControls("Car Front Light", {
    color: { value: "#ffffff" },
    metalness: { value: 0, min: 0, max: 1 },
    roughness: { value: 0.1, min: 0, max: 1 },
    emissiveIntensity: { value: 1, min: 0, max: 10 },
  })

  const rearLightControls = useControls("Car Rear Light", {
    color: { value: "#ff0000" },
    metalness: { value: 0, min: 0, max: 1 },
    roughness: { value: 0.1, min: 0, max: 1 },
    emissiveIntensity: { value: 1, min: 0, max: 10 },
  })

  const misc1Controls = useControls("Car Material.004", {
    color: { value: "#666666" },
    metalness: { value: 0.5, min: 0, max: 1 },
    roughness: { value: 0.5, min: 0, max: 1 },
  })
  const misc2Controls = useControls("Car Material.001", {
    color: { value: "#888888" },
    metalness: { value: 0.3, min: 0, max: 1 },
    roughness: { value: 0.6, min: 0, max: 1 },
  })

  useEffect(() => {
    // materials.Base.color.set(baseControls.color)
    // materials.Base.metalness = baseControls.metalness
    // materials.Base.roughness = baseControls.roughness

    // materials.Front_Wheel_Material.color.set(wheelControls.color)
    // materials.Front_Wheel_Material.metalness = wheelControls.metalness
    // materials.Front_Wheel_Material.roughness = wheelControls.roughness

    // materials.TeslaFrontLight.color.set(frontLightControls.color)
    // materials.TeslaFrontLight.metalness = frontLightControls.metalness
    // materials.TeslaFrontLight.roughness = frontLightControls.roughness
    // materials.TeslaFrontLight.emissive = new THREE.Color(
    //   frontLightControls.color
    // )
    // materials.TeslaFrontLight.emissiveIntensity =
    //   frontLightControls.emissiveIntensity

    // materials.TeslaRearLight.color.set(rearLightControls.color)
    // materials.TeslaRearLight.metalness = rearLightControls.metalness
    // materials.TeslaRearLight.roughness = rearLightControls.roughness
    // materials.TeslaRearLight.emissive = new THREE.Color(rearLightControls.color)
    // materials.TeslaRearLight.emissiveIntensity =
    //   rearLightControls.emissiveIntensity

    // materials["Material.004"].color.set(misc1Controls.color)
    // materials["Material.004"].metalness = misc1Controls.metalness
    // materials["Material.004"].roughness = misc1Controls.roughness

    // materials["Material.001"].color.set(misc2Controls.color)
    // materials["Material.001"].metalness = misc2Controls.metalness
    // materials["Material.001"].roughness = misc2Controls.roughness

    Object.values(materials).forEach((mat) => {
      mat.needsUpdate = true
    })
  }, [
    baseControls,
    wheelControls,
    frontLightControls,
    rearLightControls,
    misc1Controls,
    misc2Controls,
    materials,
  ])

  const {
    color: controlledColor,
    metalness: controlledMetalness,
    roughness: controlledRoughness,
  } = useControls("Cybertruck Materials", {
    color: defaultColor,
    metalness: { value: defaultMetalness, min: 0, max: 1, step: 0.01 },
    roughness: { value: defaultRoughness, min: 0, max: 1, step: 0.01 },
  })

  useEffect(() => {
    Object.values(materials).forEach((mat) => {
      mat.color.set(controlledColor)
      mat.metalness = controlledMetalness
      mat.roughness = controlledRoughness
      mat.needsUpdate = true
    })
  }, [controlledColor, controlledMetalness, controlledRoughness, materials])

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    const rotationSpeed = -4 * t
    if (frontWheelRef.current) frontWheelRef.current.rotation.y = rotationSpeed
    if (backWheelRef.current) backWheelRef.current.rotation.y = rotationSpeed
  })

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Base}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.Front_Wheel_Material}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.TeslaFrontLight}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.TeslaRearLight}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Material.004"]}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials["Material.001"]}
        castShadow
        receiveShadow
      />
      <mesh
        ref={backWheelRef}
        geometry={nodes.Back_Wheel.geometry}
        material={materials.Front_Wheel_Material}
        position={[-1.121, -0.185, -0.007]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.17, 0.135, 0.17]}
        castShadow
        receiveShadow
      />
      <mesh
        ref={frontWheelRef}
        geometry={nodes.Front_Wheel.geometry}
        material={materials.Front_Wheel_Material}
        position={[1.166, -0.185, -0.007]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.17, 0.14, 0.17]}
        castShadow
        receiveShadow
      />
    </group>
  )
}

useGLTF.preload(getFullPath("/tesla_cybertruck-transformed.glb"))
